name: Prayer Times Widget

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:

jobs:
  update-widget:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Take Screenshot
        run: node ./.github/scripts/screenshot.js

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Update prayer times widget"
          file_pattern: prayer-widget.png
